// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package mail

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Data struct {
	Version              int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	EncryptedLocation    []byte   `protobuf:"bytes,2,opt,name=encryptedLocation,proto3" json:"encryptedLocation,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_66c203777cc9510b, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Data) GetEncryptedLocation() []byte {
	if m != nil {
		return m.EncryptedLocation
	}
	return nil
}

func (m *Data) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "mail.Data")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_66c203777cc9510b) }

var fileDescriptor_data_66c203777cc9510b = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x51, 0x4a, 0xe2, 0x62,
	0x71, 0x49, 0x2c, 0x49, 0x14, 0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x93,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x85, 0x74, 0xb8, 0x04, 0x53, 0xf3, 0x92, 0x8b,
	0x2a, 0x0b, 0x4a, 0x52, 0x53, 0x7c, 0xf2, 0x93, 0x13, 0x4b, 0x40, 0x6a, 0x98, 0x14, 0x18, 0x35,
	0x78, 0x82, 0x30, 0x25, 0x84, 0x84, 0xb8, 0x58, 0x32, 0x12, 0x8b, 0x33, 0x24, 0x98, 0xc1, 0x0a,
	0xc0, 0xec, 0x24, 0x36, 0xb0, 0x85, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x7a, 0xab,
	0x4b, 0x7e, 0x00, 0x00, 0x00,
}
